[2024-03-12T21:22:21.021+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag-starwars.my_task manual__2024-03-12T21:22:18.956255+00:00 [queued]>
[2024-03-12T21:22:21.027+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag-starwars.my_task manual__2024-03-12T21:22:18.956255+00:00 [queued]>
[2024-03-12T21:22:21.027+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-12T21:22:21.036+0000] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): my_task> on 2024-03-12 21:22:18.956255+00:00
[2024-03-12T21:22:21.043+0000] {standard_task_runner.py:60} INFO - Started process 353 to run task
[2024-03-12T21:22:21.046+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag-starwars', 'my_task', 'manual__2024-03-12T21:22:18.956255+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dag-starwars.py', '--cfg-path', '/tmp/tmp9owul7yb']
[2024-03-12T21:22:21.048+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask my_task
[2024-03-12T21:22:21.108+0000] {task_command.py:423} INFO - Running <TaskInstance: dag-starwars.my_task manual__2024-03-12T21:22:18.956255+00:00 [running]> on host 2723c3746dd0
[2024-03-12T21:22:21.179+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag-starwars' AIRFLOW_CTX_TASK_ID='my_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-12T21:22:18.956255+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-12T21:22:18.956255+00:00'
[2024-03-12T21:22:21.184+0000] {logging_mixin.py:188} INFO - oooi
[2024-03-12T21:22:21.184+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-03-12T21:22:21.194+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=dag-starwars, task_id=my_task, execution_date=20240312T212218, start_date=20240312T212221, end_date=20240312T212221
[2024-03-12T21:22:21.221+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-12T21:22:21.234+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
